databases:
  - name: imfundo
    databaseName: imfundo_8npa
    user: imfundo_8npa_user

services:
  - type: web
    name: smmartbudget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: imfundo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false