default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Siphose1
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_App_V2_development

test:
  <<: *default
  database: Budget_App_V2_test

production:
  <<: *default
  database: Budget_App_V2_production
  username: Budget_App_V2
  password: <%= ENV["BUDGET_APP_V2_DATABASE_PASSWORD"] %>
