default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Siphose1
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_App_V2_development

test:
  <<: *default
  database: Budget_App_V2_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
